version: '3'
services:
  api:
    container_name: test_app_api
    build:
      context: .
      dockerfile: dev.api.Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      postgres_db: 
        condition: "service_healthy"
  postgres_db:
    container_name: test_app_database
    image: 'postgres:alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password_secure
    expose:
      - 5432
    volumes:
      - './db_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    external: true