[debug.databases]
test_db =  {url = "postgres://postgres:postgres@localhost/postgres"}

[release.databases]
# this test_db is meant to be used inside docker, indeed `postgres_db` refere to a docker-compose container
test_db =  {url = "postgres://postgres:password_secure@postgres_db/postgres"}


